### ISSUE TITLE
Consumo de memoria al 99%

### ISSUE THREAD

**Issue by ajteran01** [onesaitplatform/onesait-cloud-platform-community-deploy#11]
Buenas tardes, el worker node esta consumiendo el 99% de la memoria, subimos la memorioa a 64GB y nuevamente esta al 99%

Como podemos detectar que se esta consumiendo la memoria?

**Comment by lmgracia** [comment]
Hola,
Si habéis instalado la plataforma con Rancher como gestor CaaS lo más sencillo es que comprobéis a través de la propia consola de Rancher en qué módulo de los que estéis usando se consume la memoria. 
Sin más información es imposible daros más detalle, podría ser en los Notebooks si tenéis un algoritmo no optimizado, en el FlowEngine si habéis creado un flow con algún bucle, en el DataFlow,...
En la versión Enterprise el equipo de soporte podría revisar vuestra instalación y además se da acceso al una sección Manual de Operaciones que documenta casuísticas típicas, cómo monitorizar el entorno,...
