### ISSUE TITLE
Error 500 at Export Image or PDF in CE-6.0.0

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesait-cloud-platform-community-deploy#19]
Cheers,

when i want to export an image or pdf i got an Error:
![grafik](https://github.com/user-attachments/assets/fe7d9303-91b5-4201-8171-762badf19a95)
![grafik](https://github.com/user-attachments/assets/1c54fe03-4456-4574-a9cd-e5fb35a47811)

 In Logs of controlpanel i got error, that dashboardexportservice does not resolve. Is it possible to publish the service as CE?

Thanks in advance!

Best wishes

UncleDinoso

**Comment by lmgracia** [comment]
Nice to greet you again UncleDinoso,

It is true that until now we had not included that module in the CE version, but following our policy we will publish it in the next CE version, which as you know we will publish next October 12.

If at any time you have any doubts about the platform support model in the EE version, please do not hesitate to comment.

Yours sincerely.

**Comment by UncleDinoso** [comment]
Thank you ;-)
