### ISSUE TITLE
RTDB Maintainer

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesait-cloud-platform-community-deploy#20]
Cheers,

i tried the RTDB Maintainer Image in CE-6.0.0 from https://hub.docker.com/r/onesaitplatform/rtdbmaintainer, which links to this repo.

But at starting there are errors, that scheduled_job table and scheduler_table not present on ConfigDB. Thats correct, the configinitservice does not create these tables.

![grafik](https://github.com/user-attachments/assets/c090b6e0-9b3d-40c9-87df-8a23bfe5bfb7)

![grafik](https://github.com/user-attachments/assets/7e8d3cbc-4f4e-4eaf-81f1-4e5c4ba3c835)

At sourcecoude i have found, that RTDM Maintainer links to Planner Service, which is not part of CE.

Maybe there is a missing service for correct working of RTDB Maintainer?

Thank you in advance!

Best wishes

UncleDinsoso

**Comment by lmgracia** [comment]
Hi @UncleDinoso 
We have tested the CE version again and the module starts perfectly.
![image](https://github.com/user-attachments/assets/73d94c68-a6a5-4c53-adce-77f726d00a92)
We have also checked that the tables are created and with data:
![image](https://github.com/user-attachments/assets/f0702cc3-b787-4aea-94af-79680d089841)

if you like, as we are going to release version 6.1-CE this week we will wait to see if this one works for you.

**Comment by UncleDinoso** [comment]
I evaluate CE-6.1.0 and will give them i try.

**Comment by UncleDinoso** [comment]
okay, it seems, that rtdbmainter is working now. Thank you :-)
Hint: the env variable SCHEDULERDBBUSER and SCHEDULERDBBPASS contains double B instead single B like the other services ;-)
