### ISSUE TITLE
Keycloak Session Error

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesait-cloud-platform-community-deploy#21]
Cheers,

since CE-6.0.0 and using keycloak as identity provider i will receive sometime an 502 error code after login in keycloak login form.

![grafik](https://github.com/user-attachments/assets/9461c049-d1a3-4a6c-915b-ed6dc820684e)

I think, its an error with expired token but i'm not sure.

When its happened, controlpanel can not open and i have to delete the session in keycloak an delete cookies in browser.

I didn't change settings in keycloak, everthing is managed by keycloak-manager.

In CE-6.1.0 is the same behavior.

Best wishes

UncleDinoso

**Comment by prubiog** [comment]
Hi,

how do you deploy the images? Sometimes it is related to nginx configuration (proxy_buffer_size) or the ingress if it is deployed in kubernetes. Check those parameters in your installation. In our charts and community-deploy is configured and it works fine.

Best Regards,
Onesait Platform Support Team

**Comment by UncleDinoso** [comment]
Hy, thank you for your fast reply. I use nginx. I will adjust the proxy_buffer_size and give them a try. :-)

**Comment by UncleDinoso** [comment]
Hy, with a adjusted proxy_buffer_size it works now as expected. Thank you for the hint.
