### ISSUE TITLE
CE-6.1.0 Zepplin Notebook UI not showing

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesait-cloud-platform-community-deploy#22]
Cheers,

in CE-6.0.0 and 6.1.0 we encounter the problem, that the ui of zepplin is not showing:
![grafik](https://github.com/user-attachments/assets/b5bdb02f-d0f0-4761-b51f-4d7d9a40a3d8)

In CE-5.2.0 there wasn't this issue.

The Notebook is created successfully and we can download the json:
`{"noteParams":{},"angularObjects":{},"ospInfo":{"owner":"administrator","authorizations":[]},"name":"123456","noteForms":{},"defaultInterpreterGroup":"spark","id":"2KB4UA8YH","paragraphs":[{"jobName":"paragraph_1729516804563_1223596491","settings":{"params":{},"forms":{}},"progressUpdateIntervalMs":500,"runtimeInfos":{},"title":"","dateUpdated":"2024-10-21 13:20:04.565","dateCreated":"2024-10-21 13:20:04.563","progress":0,"text":"","id":"paragraph_1729516804563_1223596491","user":"anonymous","config":{"title":true},"apps":[],"status":"READY"}],"version":"0.10.1_5.1.0-osp","config":{"isZeppelinNotebookCronEnable":false},"info":{}}`
![grafik](https://github.com/user-attachments/assets/bf584ec5-301b-4857-8015-15470a31321f)

The ui bug affects all zepplin related links:
![grafik](https://github.com/user-attachments/assets/636d25ee-0dbd-4520-a8f2-fc723c4c5acd)

Best wishes

UncleDinoso

**Comment by prubiog** [comment]
Hi,

maybe you don't have some configuration applied. Have you changed the notebooks image to the new one 6-ce?. You should also activate the authentication with Keycloak in Controlpanel (var env NOTEBOOKPLATFORMAUTH=true) and Zeppelin (USE_KEYCLOAK=true, this one is true by default).

Best Regards,
Onesait Platform Support Team

**Comment by UncleDinoso** [comment]
Dear prubiog,

thank you for your answer. I added NOTEBOOKPLATFORMAUTH=true, that was missing. Now I can open "Manage Interpreters", "Helium", "Configuration" and "Job Manager".
But when i open a Notebook, i get an Websocket Error:
![grafik](https://github.com/user-attachments/assets/72856eb7-d338-4920-8b76-2119107239c8)

My nginx configuration is the same you published:
`location controlpanel/notebooks/app/ws {
	proxy_pass http://zeppelin:8080/ws;
	
	# WebSocket support
	proxy_http_version 1.1;
	proxy_set_header Upgrade websocket;
	proxy_set_header Connection "upgrade";
	proxy_read_timeout 86400;			
} `

**Comment by UncleDinoso** [comment]
Hy, it was an missing slash in nginx location configuration.
