### ISSUE TITLE
notebooks image and networks name

### ISSUE THREAD

**Issue by gerarjw** [onesaitplatform/onesait-cloud-platform-community-deploy#3]

**Comment by mmorancassy** [comment]
Hi @gerarjw !

What this issue is supossed to be? could you add more detail please?

Thanks in advance.

Miguel.M

**Comment by gerarjw** [comment]
El contenedor de los notebooks, que apunte a la imagen de nuestro registry, y los nombres de las redes no coinciden en algunos casos (a veces datanetwork, a veces op_data_network, otras opdata_network)

**Comment by ebustosm** [comment]
Hola @gerarjw,
Voy a revisar esto pero los nombres de las redes se crean de la siguiente manera en docker:
{folder}_{networkName}.

La red inicial se crea en el docker-compose de persistencia (op_data) con nombre "datanetwork" así que la red se debería crear como op_data_datanetwork según el patrón, de esa manera, al levantar los módulos (op_modules) deben hacer referencia a la red creada.

Cuando haga una revisión, actualizo el hilo.

Muchas gracias por avisarnos!

**Comment by gerarjw** [comment]
Hola Edu,

Al crear la red del directorio op_data se crea como opdata_datanetwork, o al menos me pasa a mi :(. Con actualizar los nombres de las redes de los módulos a opdata_datanetwork debería valer.

Gracias!

**Comment by mmorancassy** [comment]
Hi @gerarjw @ebustosm !

It would be better if you write your issue in english ;)

Kind regards,
Miguel.M

**Comment by onesaitplatform** [comment]
Hi @gerarjw,

We are going to check this issue, when we have finished update the repo. 

Thank you so much

**Comment by mmorancassy** [comment]
Hi @gerarjw 

We have tested on Digital Ocean Droplet with Ubuntu 18 and the result is the same on CentOS 7, it worked, and we did not see any problem with docker network:

![Captura de pantalla 2019-10-03 a las 15 54 13](https://user-images.githubusercontent.com/15340414/66137291-2878c200-e5fd-11e9-840e-4139cc6eb9cd.png)

![Captura de pantalla 2019-10-03 a las 15 54 03](https://user-images.githubusercontent.com/15340414/66137309-2f073980-e5fd-11e9-9057-c2c74ae4d749.png)

Kind regards,
Miguel.M
