### ISSUE TITLE
Environment variable missing on op-data docker-compose.initdb.yml

### ISSUE THREAD

**Issue by renetashi** [onesaitplatform/onesait-cloud-platform-community-deploy#6]
There is an environment variable missing in the docker-compose.initdb.yml in the "op-data" directory

- LOADMONGODB=false

**Comment by onesaitplatform** [comment]
Solved
![image](https://user-images.githubusercontent.com/44359141/95076999-0d122c80-0713-11eb-9ed2-2fee26416dad.png)
